# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_macos64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_macos64)
  Sagittar_config = debug_macos64

else ifeq ($(config),debug_linux64)
  Sagittar_config = debug_linux64

else ifeq ($(config),debug_windows64)
  Sagittar_config = debug_windows64

else ifeq ($(config),test_macos64)
  Sagittar_config = test_macos64

else ifeq ($(config),test_linux64)
  Sagittar_config = test_linux64

else ifeq ($(config),test_windows64)
  Sagittar_config = test_windows64

else ifeq ($(config),test_release_macos64)
  Sagittar_config = test_release_macos64

else ifeq ($(config),test_release_linux64)
  Sagittar_config = test_release_linux64

else ifeq ($(config),test_release_windows64)
  Sagittar_config = test_release_windows64

else ifeq ($(config),release_macos64)
  Sagittar_config = release_macos64

else ifeq ($(config),release_linux64)
  Sagittar_config = release_linux64

else ifeq ($(config),release_windows64)
  Sagittar_config = release_windows64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Sagittar

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Sagittar:
ifneq (,$(Sagittar_config))
	@echo "==== Building Sagittar ($(Sagittar_config)) ===="
	@${MAKE} --no-print-directory -C . -f Sagittar.make config=$(Sagittar_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Sagittar.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_macos64"
	@echo "  debug_linux64"
	@echo "  debug_windows64"
	@echo "  test_macos64"
	@echo "  test_linux64"
	@echo "  test_windows64"
	@echo "  test_release_macos64"
	@echo "  test_release_linux64"
	@echo "  test_release_windows64"
	@echo "  release_macos64"
	@echo "  release_linux64"
	@echo "  release_windows64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Sagittar"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"